ALTER TABLE ProductInfo MODIFY ProductNo int AUTO_INCREMENT ;
ALTER TABLE ProductInfo AUTO_INCREMENT=100001;

ALTER TABLE CustomerInfo MODIFY CustomerNo int AUTO_INCREMENT ;
ALTER TABLE CustomerInfo AUTO_INCREMENT=100001;
